In [1]:
import torch

In [14]:
# design model -> logistic regression predicts if something is true or false instead of predicting a continous value
# the logistic curves tells the 'probability' of some dependent x and maps it to an independent y(true or false) 
# feedforward loop
# backward pass
# weight updates

class LogisticRegressionBinary(torch.nn.Module):
    def __init__(self, input_dimension, output_dimension):
        super(LogisticRegressionBinary, self).__init__()
        self.Dense = torch.nn.Linear(input_dimension, input_dimension)
        
        
    def forward(self, x):
        x = self.Dense(x)
        x = torch.sigmoid(x)
        return x

# training

In [26]:
x = torch.tensor([[1.0], [3.0], [5.6], [6.2]])
y = torch.tensor([[1.0], [1.0], [0.0], [0.0]])
x, y

(tensor([[1.0000],
         [3.0000],
         [5.6000],
         [6.2000]]),
 tensor([[1.],
         [1.],
         [0.],
         [0.]]))

In [70]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [72]:
dataset = datasets.load_breast_cancer()
x, y = dataset.data, dataset.target

In [75]:
std_scaler = StandardScaler()

In [76]:
print(x[0])
print()

[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
 1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
 6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
 1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
 4.601e-01 1.189e-01]


In [45]:
model = LogisticRegressionBinary(x.shape[1], 1)

In [64]:
loss = torch.nn.BCELoss()
optim = torch.optim.SGD(model.parameters(), lr=1)

for epoch in range(20):
    for data, target in zip(x, y):
        y_pred = model(data)
        cost = loss_fn(y_pred, target)
        
        cost.backward()
        optim.step()
        optim.zero_grad()
        print(f'At the current {epoch} the cost is: {cost}.')

In [65]:
for epoch in range(100):
    for data, target in zip(x, y):
        y_pred = model(data)
        cost = loss_fn(y_pred, target)
        
        cost.backward()
        optim.step()
        optim.zero_grad()
        print(f'At the current {epoch} the cost is: {cost}.')

At the current 0 the cost is: 0.12679053843021393.
At the current 0 the cost is: 0.14065347611904144.
At the current 0 the cost is: 0.9163644313812256.
At the current 0 the cost is: 0.3891364634037018.
At the current 1 the cost is: 0.5352098345756531.
At the current 1 the cost is: 0.9529882669448853.
At the current 1 the cost is: 5.795087645310559e-07.
At the current 1 the cost is: 9.504608300403561e-08.
At the current 2 the cost is: 0.3151179552078247.
At the current 2 the cost is: 0.803104043006897.
At the current 2 the cost is: 0.007091853767633438.
At the current 2 the cost is: 0.0012933171819895506.
At the current 3 the cost is: 0.08721064776182175.
At the current 3 the cost is: 0.32322055101394653.
At the current 3 the cost is: 0.896543562412262.
At the current 3 the cost is: 0.15370196104049683.
At the current 4 the cost is: 0.19023510813713074.
At the current 4 the cost is: 0.7734925150871277.
At the current 4 the cost is: 0.010995269753038883.
At the current 4 the cost is: 0.0

At the current 69 the cost is: 0.000454304477898404.
At the current 70 the cost is: 3.261097299400717e-05.
At the current 70 the cost is: 0.024261081591248512.
At the current 70 the cost is: 0.012086901813745499.
At the current 70 the cost is: 0.0004540730733424425.
At the current 71 the cost is: 3.161592758260667e-05.
At the current 71 the cost is: 0.02387528121471405.
At the current 71 the cost is: 0.011895375326275826.
At the current 71 the cost is: 0.000453696062322706.
At the current 72 the cost is: 3.066599674639292e-05.
At the current 72 the cost is: 0.023503554984927177.
At the current 72 the cost is: 0.011710813269019127.
At the current 72 the cost is: 0.0004531817976385355.
At the current 73 the cost is: 2.9759812605334446e-05.
At the current 73 the cost is: 0.02314520813524723.
At the current 73 the cost is: 0.011532783508300781.
At the current 73 the cost is: 0.00045254267752170563.
At the current 74 the cost is: 2.8894126444356516e-05.
At the current 74 the cost is: 0.0227

In [69]:
model(x[3])

tensor([0.0197], grad_fn=<SigmoidBackward>)